smartlight/__init__.py
from flask import Flask

from smartlight.animations import Animations


# Set up Flask App
app = Flask(__name__)

app.config.from_object('config')

animation_thread = Animations(app=app)

from smartlight.controllers import main
app.register_blueprint(main)

smartlight/controllers.py
from flask import Blueprint, render_template

from smartlight import animation_thread
from smartlight.utils import error_to_json

import json

main = Blueprint('main', __name__)


@main.route('/')
def index():
    """
    Control for the index/main page

    :return: html response with main page
    """
    return render_template('main.html')


@main.route('/color/name/<name>')
@error_to_json
def set_color_name(name):
    """
    Sets the color of the connected light.

    :param name: CSS name of the color to set the light to
    :return: json string with success status and message
    """
    animation_thread.stop()
    animation_thread.set_color(name=name)
    return json.dumps({'status': 'success', 'message': 'Set color to ' + name})


@main.route('/color/hex/<hex>')
@error_to_json
def set_color_hex(hex):
    """
    Sets the color of the connected light.

    :param hex: hex value of the color to set the light to
    :return: json string with success status and message
    """
    animation_thread.stop()
    animation_thread.set_color(hex='#'+hex)
    return json.dumps({'status': 'success', 'message': 'Set color to #' + hex})


@main.route('/color/rgb/<int:r>/<int:g>/<int:b>')
@error_to_json
def set_color_rgb(r, g, b):
    """
    Sets the color of the connected light.

    :param r: intensity 0-255 of the red channel
    :param g: intensity 0-255 of the green channel
    :param b: intensity 0-255 of the blue channel
    :return: json string with success status and message
    """
    animation_thread.stop()
    animation_thread.set_color(red=r, green=g, blue=b)
    message = 'Set color to rgb %d, %d, %d' % (r, g, b)
    return json.dumps({'status': 'success', 'message': message})


@main.route('/color/')
@main.route('/color')
@error_to_json
def get_color_rgb():
    """
    Gets the color of the connected light

    :return: json string with success status, message and current color
    """
    color = animation_thread.get_color()
    message = 'Current color ' + str(color)
    return json.dumps({'status': 'success', 'message': message, 'color': color})


@main.route('/color/off/')
@main.route('/color/off')
@error_to_json
def turn_off():
    """
    Switches the light off
    :return: json string with success status and message
    """
    animation_thread.stop()
    animation_thread.turn_off()
    message = 'Turned light off'
    return json.dumps({'status': 'success', 'message': message})


@main.route('/animation/stop')
@error_to_json
def animation_stop():
    """
    Stops the current animation
    :return: json string with success status and message
    """
    animation_thread.stop()
    message = 'Animations stopped'
    return json.dumps({'status': 'success', 'message': message})


@main.route('/animation/random')
@error_to_json
def animation_random():
    """
    Starts random animation: morphing from one random color to the next
    :return: json string with success status and message
    """
    animation_thread.random()
    message = 'Random started'
    return json.dumps({'status': 'success', 'message': message})


@main.route('/animation/fire')
@error_to_json
def animation_fire():
    """
    Starts fire animation: morphing from a color from the fire palette to the next at random speeds
    :return: json string with success status and message
    """
    animation_thread.fire()
    message = 'Fire started'
    return json.dumps({'status': 'success', 'message': message})


@main.route('/animation/strobe')
@error_to_json
def animation_strobe():
    """
    Starts strobe light: at about 10Hz frequency
    :return: json string with success status and message
    """
    animation_thread.strobe()
    message = 'Strobe started'
    return json.dumps({'status': 'success', 'message': message})

smartlight/templates/main.html
<html>
<head>
    <meta name=viewport content="width=device-width,initial-scale=1">
    <title>Flask-SmartLight Interface</title>
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/jquery.simplecolorpicker.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/main.css') }}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2 text">
                <h1><strong>Flask-SmartLight</strong> Control&nbsp;panel</h1>
                <div class="description">
                    <p>
                        Control your Blinkstick from anywhere !
                    </p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-lg-offset-4 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2">
                    <div class="text-center">
                        <select name="colorpicker">
                          <option value="#FF0000">Red</option>
                          <option value="#FF5A00">Red orange</option>
                          <option value="#FFAD00">Orange</option>
                          <option value="#FFDE00">Yellow</option> <br />
                          <option value="#D0FF00">Light green</option>
                          <option value="#45FF00">Bold green</option>
                          <option value="#00B945">Dark green</option>
                          <option value="#002ED0">Deep Blue</option> <br />
                          <option value="#3A0BF9">Blue</option>
                          <option value="#911DF1">Purple</option>
                          <option value="#C34CEF">Violet</option>
                          <option value="#EE82EE">Pink</option>
                        </select>
                        <hr />
                        <span id="animations" class="inline">
                            <a href="{{ url_for('main.animation_random') }}" class="animation"><img src="{{ url_for('static', filename='img/random.png') }}" alt="Random"/></a>
                            <a href="{{ url_for('main.animation_fire') }}" class="animation"><img src="{{ url_for('static', filename='img/fire.png') }}" alt="Fire"/></a>
                            <a href="{{ url_for('main.animation_strobe') }}" class="animation"><img src="{{ url_for('static', filename='img/strobe.png') }}" alt="Strobe"/></a>
                            <a href="{{ url_for('main.turn_off') }}" class="animation"><img src="{{ url_for('static', filename='img/off.png') }}" alt="Off"/></a>
                        </span>
                        <hr />
                        <div class="alert-area center-block">
                            <div  class="alert alert-success" role="alert"><span id="message">Select a color</span></div>
                        </div>
                    </div>
            </div>
        </div>
    </div>



<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.simplecolorpicker.js') }}"></script>
<script>
    $('select[name="colorpicker"]').simplecolorpicker();
    $('select[name="colorpicker"]').simplecolorpicker({
        picker: true
    }).on('change', function() {
        $('#message').fadeOut( 100 );

        var url = '{{ url_for('main.set_color_hex', hex='') }}' + $( this ).val().replace('#','');
        $.getJSON( url, function(data) {
            var text = data['message'];
            $('#message').text(text);
            $('#message').fadeIn( 100 );
        });
    });

    $('.animation').click( function( event ) {
        event.preventDefault();

        var url = $( this ).attr('href');

        $.getJSON( url, function(data) {
            var text = data['message'];
            $('#message').fadeOut( 100 );
            $('#message').text(text);
            $('#message').fadeIn( 100 );
        });

    });
</script>
</body>
</html>